site_name: Project Documentation
theme:
  name: "material"
plugins:
  - mkdocstrings
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - How-to Guide: howtoguide.md
  - Explanation: explanation.md
  - Reference: reference.md
